### ISSUE TITLE
FM-I3: Add example showing qualification of the reference by the how instead of the why.

### ISSUE THREAD

**Issue by JervenBolleman** [FAIRMetrics/Metrics#14]
While semantic respecting biology etc... would be nice sometimes all we can do is 'mappedBecauseSequenceSimilarEnough' in many bio cases or 'linkedBecauseFoundInSameStolenArtCache' for some unfortunate art. Basically an example showing that this kind of thing is acceptable would be nice.

**Comment by markwilkinson** [comment]
done
