### ISSUE TITLE
FM-F3: How specific is the meta-data that should be preserved?

### ISSUE THREAD

**Issue by JervenBolleman** [FAIRMetrics/Metrics#17]
2 things here. I think this can be made into 2 requirements, a data preservation plan. Which could be as little as "will be left running as long as the machine doesn't crash and the university doesn't fire me" too "as long as the NIH will exist".

Regarding the meta-data, even preserving minimal meta-data on each resource in a dataset can be a real expense. How much are we allowed to cut out?

**Comment by micheldumontier** [comment]
we have a greater expectation from the data preservation plan... but the exact requirements remains to be clarified. but here, at least, we ask you to think about that and make it public.

i don't agree that preserving minimal metadata is a real expense. please evidence.

**Comment by JervenBolleman** [comment]
I think my minimal might be more maximal that your minimal ;) Given the 4 billion or so identifiable resources in an UniProt release. Just keeping track of all of them is more expensive than keeping track of the primary accessions that we do now. For most of them we don't even generate independent meta-data now. if the meta-data is more granular e.g. describing a certain release then it is not much of an issue at all.

Also, some identifiers have been removed for legal reasons and may never ever be made retrievable again (major screw up at some medical sequencing centre). Not sure on how to square that with the requirement.

**Comment by micheldumontier** [comment]
you can always use a file based system, rather than a triple store for the metadata. lots of efficient implementation options available that providers will need to explore. i don't think this argument squares with meeting the expectations set out by the FAIR principles.

In what way is the metric not computable?

**Comment by JervenBolleman** [comment]
The meta-data that is required to be preserved is not well defined and therefore not _yet_ computable. The lack of clear definition means expense of storing and providing it long term are not clear. 

To be clear I was actually thinking of files as well, but enough permanent files also have an expense. Files must still be retrievable and their IRIs can't change so pragmatically it must be available via http and that comes with a certain cost when looking at decades plus. 

i.e. just the identifiers in a single column for a medium sized dataset like UniProt trends towards 100+ gigabytes. Times 12 per year, times decade running time and a small bill starts to appear. If more meta-data than just the identifiers must be preserved this costs goes up again. e.g. just adding a date adds cost to maintain. 

It could be done cheaper but basically what I want to see is a clear definition and examplar of what meta-data must be preserved and for which resources. The current spec is not clear.

**Comment by krobasky** [comment]
Myself and a student are working on a FAIR meta-data requirement spec that cross-references each requirement to a FAIR requirement from the community. We've only just started on this about a week or two ago, and are pretty early-in, so I'd be interested in knowing if anyone else is working on something similar.

**Comment by micheldumontier** [comment]
i'd be interested in working with you on a metadata spec!

**Comment by krobasky** [comment]
Yes please! I’m trying to map it to HCLS vocabulary, it’s not easy.

**Comment by micheldumontier** [comment]
You want to use the HCLS vocabulary for providing dataset metadata, but I don't think it would fit as metadata for FAIRness assessments.

**Comment by micheldumontier** [comment]
@JervenBolleman we expect communities to define and adopt a metadata standard that complies with the FAIR principles and in accordance to their data management plan. you are free to propose such a standard and you are free to elaborate what commitment you have via a public data management plan.

**Comment by markwilkinson** [comment]
closing as it is a gen1 metric issue
