### ISSUE TITLE
FAIR Evaluator demonstration service not working

### ISSUE THREAD

**Issue by DrMaggie** [FAIRMetrics/Metrics#28]
It is stated in the document https://github.com/FAIRMetrics/Metrics/blob/master/README.md that "With the goal of providing an objective, automated way of testing (meta)data resources against the Metrics, the Metrics Authorship Group have created the FAIR Evaluator, which is running as a demonstration service at http://linkeddata.systems:3000. " 
While this page itself is available, Unfortunately, none of the links to information or resources seem to work at the moment - the result is the error message "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. If you are the application owner check the logs for more information." 
If the demonstrator is no longer available, it would be very helpful if information about this would be added in the documentation.

**Comment by markwilkinson** [comment]
Hi!
The entire system is currently down for a top-to-bottom redesign.  I will remove the references to the demonstration server.  I'm hoping to have the new server up for public access in early February.
Sorry to waste your time!
Mark
