### ISSUE TITLE
error in PDF rendering

### ISSUE THREAD

**Issue by egonw** [FAIRMetrics/Metrics#29]
The `>` character needs to be escaped in LaTeX, or you get this:

![image](https://user-images.githubusercontent.com/26721/51239371-7f5c3f80-1979-11e9-9edb-27df722a551d.png)

**Comment by markwilkinson** [comment]
I think its better for me to eliminate the latex entirely.  I thought it would be useful at first, but... it really isn't much more useful than plain text.

**Comment by egonw** [comment]
Agreed, a bit of markdown can be much better.

**Comment by egonw** [comment]
Not sure... if so, then I'm also guilty as charged.
