### ISSUE TITLE
Reformulate FM-I3 rationale

### ISSUE THREAD

**Issue by csarven** [FAIRMetrics/Metrics#32]
re https://purl.org/fair-metrics/FM_I3 rationale:

>One of the reasons that HTML is not suitable for machine-readable knowledge representation is that the hyperlinks between one document and another do not explain the nature of the relationship - it is 'unqualified'.  For Interoperability, the relationships within and between data must be more semantically rich than 'is (somehow) related to'.

Perhaps not intended but, the way that assertion comes across (to me) is as if HTML in its entirety incapable of semantically expressing "the nature of the relationship".

Given generic "related to" doesn't qualify, the assertion about HTML's machine-readability in context of hyperlinks would **only** be true *if* the element in which the hyperlink occurs does not, for instance include `rel`, `rev` (plain ol' HTML), `property`, `typeof` (RDFa) attributes.

So, if you mean to say an `<a>` in HTML without eg. `rel`, would not qualify as it would only signal a generic "related to" and that is not "semantically rich" enough, then say that exactly. However, once `rel`, `rev`, `property`, `typeof` attributes are involved, whether in HTML or XML family (SVG, MathML), it would qualify just fine towards interoperability. The whole notion of RDF in markup languages (primarily talking about RDFa here, as opposed to including data using other RDF syntax in `script`) is based off the idea of being able to include additional semantics into the host language! I'm pretty sure that when HTML and RDFa went through, they had some idea about how to achieve "interoperability" :)

What I suggest is to reformulate the intention along the lines of "Knowledge is expected to be expressed in a way that can advertise the specific nature of the relationship between units of information". It is already a grey area as to what's too generic and that specific would be preferable. For example, we can consider `<a>` without attributes to be generic, but does that same rationale fit for other knowledge representations having only one way of relating information? This should also be clarified in the rationale IMO.

**Comment by micheldumontier** [comment]
Thanks Sarven. I propose a rewrite to:

Knowledge is expected to be expressed in a way that can articulate the specific nature of the relationship between units of information. For instance, the nature of hyperlinks embedded in HTML documents should be augmented using rel or rev, property, typeof (RFDa) attributes.  Numerous ontologies provide richer relations.  For example, SKOS offers relations for terminologies (e.g. exact matches), or the semanticscience integrated ontology for expressing roles of entities in complex processes (e.g. has participant, has role, is realized in).  The semantics of the relationship do not need to be 'strong' - for example, 'objectX  wasFoundInTheSameBoxAs objectY' is an acceptable qualified reference\n  \n  As, data silos thwart interoperability, we should reasonably expect that some of the references/relations point outwards to other resources, owned by third-parties; this is one of the requirements for 5 star linked data.

**Comment by csarven** [comment]
Sounds good to me. Just a very minor point:

I hope the intention behind "Knowledge is expected.." was clear in that the metric stays agnostic as possible about the approach taken. That is, FM-I3 doesn't expect HTML or certain attributes in HTML on a particular tag.

"For instance.." works but I'd keep it slightly simpler by removing "typeof" because of the emphasis on hyperlinks. I've initially mentioned typeof because it can link out to some concept, but not in the way of a human-actionable link of course.

How about:

"For instance, the nature of hyperlinks embedded in HTML documents can be augmented using rel, rev, or property (RDFa) attributes to relate to something with a unique identifier."

re "to relate to something with a unique identifier": in the case of using the RDF language, I'm assuming that FM-I3 expects the object of an RDF triple to be a URI as opposed to a literal. Is that right? I was trying to rule out the possibility where property is used with a literal.

Sorry if this sounds nitpicky.. just trying to be clear to you on the thought process :)

**Comment by markwilkinson** [comment]
closing a gen1 metric issue
