### ISSUE TITLE
link broken: Horizon 2020 Commission expert group on Turning FAIR data into reality

### ISSUE THREAD

**Issue by katrinleinweber** [FAIRMetrics/Metrics#6]
http://ec.europa.eu/transparency/regexpert/index.cfm?do=groupDetail.groupDetail&groupID=3464&NewSearch=1&NewSearch=1 in [ReadMe.md](https://github.com/FAIRMetrics/Metrics/blame/master/README.md#L25). 

Nothing in WayBackMachine, but in https://webcache.googleusercontent.com/search?q=cache:http://ec.europa.eu/transparency/regexpert/index.cfm%3Fdo%3DgroupDetail.groupDetail%26groupID%3D3464%26NewSearch%3D1%26NewSearch%3D1&ie=utf-8&oe=utf-8&client=firefox-b-ab&gws_rd=cr&dcr=0&ei=iyogWtGQLcv1kwWtoC8

---

Name: Horizon 2020 Commission expert group on Turning FAIR data into reality (E03464)

Active

Abbreviation: FAIRdata

Policy Area: Research and Innovation

Lead DG: RTD - DG Research and Innovation

Type: Informal, Temporary

Scope: Limited

Mission: Findable, accessible, interoperable and re-usable/ re-producible (FAIR) data is an integral part in the process of opening up science and research. By improving the FAIR-ness of research data it will unlock the potential for both scientific research and society to draw from the benefits of this data, and also enable significant contribution to economic growth. Accordingly, the Open Science agenda contains the ambition to make FAIR data sharing the default for scientific research by 2020. The overall objective of the Expert Group on Turning FAIR data into reality is to operationalise and facilitate this goal.

Task: Other

The group will fulfil five essential tasks, including: 1) Mapping of existing initiatives and analysis of the components of FAIR (findable, accessible, interoperable and re-usable) to develop recommendations with a view to what needs to be done to turn each of these components into reality (on EU/ Member State/ international level); 2) Propose indicators to measure progress on each of the FAIR components; 3) Give input to a proposed action plan on how to make data FAIR; 4) Contribute to the evaluation of the Horizon 2020 DMP template and future revisions of the template, in light of harmonisation with funders across the EU, including the development of additional sector/ discipline specific guidance (if desired); 5) Provide input into the issue of costing and financing of data management activities (on EU/ Member State/ international level). The groups recommendations will be outlined and published in a Final Report.

Contact: RTD-OPEN-ACCESS@ec.europa.eu

Publication in RegExp: 25 Aug 2016

Link to Website: http://ec.europa.eu/research/participants/portal/desktop/en/experts/index.html 

Last updated: 16 Oct 2017

**Comment by markwilkinson** [comment]
Fixed - thanks!

**Comment by katrinleinweber** [comment]
You're welcome :-)
