### ISSUE TITLE
FM-I1

### ISSUE THREAD

**Issue by Jarvanerp** [FAIRMetrics/Metrics#7]
In the metrics (https://github.com/FAIRMetrics/Metrics/blob/master/Distributions/FM_I1.pdf) it is specified that another specification language other than BNF can be used. However a valid result is stated as "BNF found".  As the comments state the importance of ANAI, I was wondering if you have made progress on this topic?

**Comment by micheldumontier** [comment]
Right - so this was the starting point. We would need a list of such specification languages - do you know of such a list?

**Comment by micheldumontier** [comment]
@markwilkinson

**Comment by markwilkinson** [comment]
I will edit the metric text as soon as we have an alternative text :-)

**Comment by markwilkinson** [comment]
This is something that we need to ask FAIRSharing to deal with.  I'm assigning this one to Susanna!  :-)

**Comment by SusannaSansone** [comment]
I need to add Pete here, so I can assign it to him and the team.

**Comment by markwilkinson** [comment]
closing a Gen1 metric issue
