### ISSUE TITLE
How the test is implemented?

### ISSUE THREAD

**Issue by ammar257ammar** [FAIRMetrics/Metrics#79]
I have a question regarding the maturity indicator test. If I submitted a new maturity indicator following the Markdown and the Nanopub templates to the FAIR evaluation service, How the test is executed? the templates does not have rules for implementation (in a machine-readable way) that could be automatically consumed by a software. Does that mean, that people from your side needs to implement that or there is another approach that is not clear to me.
Thank you

**Comment by markwilkinson** [comment]
Hi!

The Markdown is for Maturity Indicators (the textual descriptions of a desirable FAIR behavior).  The Nanopubs are auto-generated, so there is no need to do that step yourself.  The **implementation** of a Maturity Indicator, in the form of an MI Test, is another step - this is not automatically done.  You have to code it yourself (or politely ask me to do it for you ;-) )

If you do a pull request on your Markdown, it will then go through a review process where we can discuss among a variety of experts whether the metric is well-formed, automatable, and correctly interpreting one of the FAIR principles.  Once it has been reviewed, I would be happy to write the test for you!  

Hope that helps!
Mark

**Comment by ammar257ammar** [comment]
Thanks a lot Mark, that is very informative. Glad to know how the process works, and I can clearly follow the steps.

Sincerely,
Ammar
